auctions/urls.py
from django.urls import path

from . import views

app_name = "auction"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("l/<str:id>", views.listing, name="listing"),
    path("create", views.create, name="create"),
    path("categories", views.category, name="categories"),
    path("c/<str:cat>", views.categoryFiltered, name="filteredByCat"),
    path("all", views.all_listings, name="allListings"),
    path("watchlist", views.watchlist, name="watchlist")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MinValueValidator
from datetime import datetime

class User(AbstractUser):

    def __str__(self):
        return f"{self.username}"

class ListingManager(models.Manager):
    def create_listing(self, user, title, url, cat1, cat2, cat3, condition, description, start_price):
        listing = self.create(user=user, title=title, url=url, cat1=cat1, cat2=cat2, cat3=cat3, condition=condition, description=description, start_price=start_price)
        return listing

# 1st Additional Model
class Listing(models.Model):
    ELECTRONICS = 'el'
    SPORTS = 'sp'
    EDUCATION = 'ed'
    BOOKS = 'bk'
    TOYS = 'ty'
    ART = 'ar'
    CLOTHES = 'cl'
    BEAUTY= 'bf'
    HOME = 'hm'
    ACCESSORIES = 'ac'
    LUXURY = 'lx'
    JEWELLERY = 'jw'
    choices = [
        ( "", ""),
        (ELECTRONICS, 'Electronics'),
        (SPORTS, 'Sports'),
        (EDUCATION, 'Education'),
        (TOYS, 'Toys'),
        (BOOKS, 'Books'),
        (ART, 'Art'),
        (LUXURY, 'Luxury'),
        (CLOTHES, 'Clothes'),
        (JEWELLERY, 'Jewellery'),
        (BEAUTY, 'Beauty and Fragrances'),
        (HOME, 'Home'),
        (ACCESSORIES, 'Accessories')
    ]
    
    NEW = "bn"
    USED_ONCE = "u1"
    USED = "us"
    condition_choices = [
        ("", ""),
        (NEW, "Brand New"),
        (USED_ONCE, "Used once"),
        (USED, 'Used')
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="listings")
    title = models.CharField(max_length=128)
    date = models.DateField(auto_now_add=True)
    url = models.URLField(blank=True)
    cat1 = models.CharField(blank=True, max_length=2, choices=choices)
    cat2 = models.CharField(blank=True, max_length=2, choices=choices)
    cat3 = models.CharField(blank=True, max_length=2, choices=choices)
    description = models.TextField()
    condition = models.CharField(blank=True, max_length=2, choices=condition_choices)
    start_price = models.DecimalField(max_digits=10, decimal_places=0)

    active = models.BooleanField(default=True)

    objects = ListingManager()

    def __str__(self):
        answer = f"{self.title} : {self.start_price}"
        if self.cat1 != '':
            answer += f", {self.cat1}"
        if self.cat2 != '':
            answer += f", {self.cat2}"
        if self.cat3 != '':
            answer += f", {self.cat3}"
        return answer

# 2nd Additional Model
class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="bids")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, blank=True, null=True, related_name="bids")
    price = models.DecimalField(max_digits=10, decimal_places=2)
    winning_Bid = models.BooleanField(default=False)
    datetime = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return f"Bid by user({self.user}) for listing({self.listing.title}) : ${self.price} | Last modified: {self.datetime}"

# 3rd Additional Model
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="comments")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, blank=True, null=True, related_name="comments")
    comment = models.TextField(blank=True)
    datetime = models.DateTimeField(auto_now_add=True, blank=True)
    ordering = ['-datetime',]

    def __str__(self):
        return f"Comment by user['{self.user}'] for listing['{self.listing}']"

class WatchListManager(models.Manager):
    def create_watchlist(self, user):
        wl = self.create(user = user)
        return wl

# 4th Additional Model 
class WatchList(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    listings = models.ManyToManyField(Listing, related_name="watchlist")

    objects = WatchListManager()

    def __str__(self):
        return f"{self.user}'s Watchlist"

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from datetime import datetime
from django.forms.models import model_to_dict 
import re

from .models import User, Listing, Bid, Comment, WatchList
from . import utils

def index(request):
    # Skip the first option in the categoryList, since it is blank
    categoryList = Listing.choices[1:]
    listing = Listing.objects.filter(active=True)
    if request.method == "POST":
        if 'listView' in request.POST:
            listView = True
            return render(request,"auctions/index.html", {
                "listing" : listing,
                "categoryList" : categoryList,
                "listView" : listView
            })
    return render(request, "auctions/index.html", {
        "listing" : listing,
        "categoryList" : categoryList
    })

def all_listings(request):
    categoryList = Listing.choices[1:]
    listing = Listing.objects.all()
    
    # Display inactive listings as well
    displayAll = True
    
    if request.method == "POST":
        if 'listView' in request.POST:
            listView = True
            return render(request,"auctions/index.html", {
                "listing" : listing,
                "categoryList" : categoryList,
                "listView" : listView
            })
    return render(request, "auctions/index.html", {
        "listing" : listing,
        "categoryList" : categoryList,
        "displayAll" : displayAll
    })


def login_view(request):
    categoryList = Listing.choices[1:]
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auction:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password.",
                "categoryList" : categoryList
            })
    else:
        return render(request, "auctions/login.html", { 
                "categoryList" : categoryList 
                })


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auction:index"))


def register(request):
    categoryList = Listing.choices[1:]
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match.",
                "categoryList" : categoryList
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken.",
                "categoryList" : categoryList
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auction:index"))
    else:
        return render(request, "auctions/register.html", {
            "categoryList" : categoryList
            })

@login_required
def create(request):
    print(request.user)
    categoryList = Listing.choices[1:]
    if request.method == "POST":
        user = request.user
        title = request.POST['title']
        description = request.POST['description']
        date = datetime.today().strftime('%Y-%m-%d')
        url = request.POST['image-url']
        cat1 = request.POST['cat1']
        cat2 = request.POST['cat2']
        cat3 = request.POST['cat3']
        start_price = request.POST['price']
        condition = request.POST['condition']
        #Create the listing
        listing = Listing.objects.create_listing(user, title, url, cat1, cat2, cat3, condition, description, start_price)
        listing.active = True
        listing.save()
        return render (request, f"auctions/create.html", {
            "listing" : listing,
            "conditionList" : Listing.condition_choices,
            "categoryList" : categoryList
        })
    return render(request, f"auctions/create.html", {
        "choices" : Listing.choices,
        "conditionList" : Listing.condition_choices,
        "categoryList" : categoryList
    })

@login_required
def listing(request, id):
    listing_is_present = False 
    categoryList = Listing.choices[1:]
    listing = Listing.objects.get(id=id)
    recentViewsList = utils.getRecentViewsList(request, listing)
    otherSellersList = utils.getOtherSellers(listing)
    for i in range(len(recentViewsList)) :
        recentViewsList[i] = Listing.objects.get(id=recentViewsList[i])
    print(recentViewsList)
    otherItemsBySeller = utils.getOtherItemsBySeller(listing)
    user = request.user
    # print(user.bids.get(listing=listing))
    winner = None
    comments = utils.getCommentList(listing)
    latestBid = utils.getLatestBid(listing)
    try: 
        watchlist = WatchList.objects.get(user=user, listings=listing)
    except WatchList.DoesNotExist:
        watchlist = None
    if watchlist != None:
        # Listing is present in the Watchlist
        listing_is_present = True 
    if latestBid !=  None:
        latestBidPrice = latestBid.price
    else:
        latestBidPrice = listing.start_price    
    try:
        if user.bids.get(listing=listing).winning_Bid == True:
            winner = user
    except Bid.DoesNotExist:
        pass
    if request.method == "POST":

        # Activate or Deactivate the Listing
        if 'toggle' in request.POST:
            listing.active = not listing.active
            listing.save()
            if listing.active == False:
                try:
                    utils.setBidWinner(listing)
                except Bid.DoesNotExist:
                    pass
                return render(request, f"auctions/listing.html", {
                "listing" : listing,
                "choices" : Listing.choices,
                "categoryList" : categoryList,
                "recentViewsList" : recentViewsList,
                "latestBidPrice" : latestBidPrice,
                "otherItemsList" : otherItemsBySeller,
                "otherSellersList" : otherSellersList,
                "listing_is_present" : listing_is_present
                })
            else:
                try:
                    utils.clearBidWinner(listing)
                except Bid.DoesNotExist:
                    pass
                return render(request, f"auctions/listing.html", {
                "listing" : listing,
                "choices" : Listing.choices,
                "categoryList" : categoryList,
                "latestBidPrice" : latestBidPrice,
                "recentViewsList" : recentViewsList,
                "otherItemsList" : otherItemsBySeller,
                "otherSellersList" : otherSellersList,
                "listing_is_present" : listing_is_present
                })

        #Add functionality for editing/deleting listing later
        elif 'edit' in request.POST or 'delete' in request.POST:
            pass
        
        # Add to Watchlist
        elif 'watchlist' in request.POST:
            utils.makeWatchList(user, listing)
            listing_is_present = True
        
        # Remove from Watchlist
        elif 'remove-watchlist' in request.POST:
            utils.removeFromWatchList(user, listing)
            listing_is_present = False
        
        # Make a Bid
        elif 'bid' in request.POST:
            bidPrice = request.POST['bidPrice']
            utils.makeBid(user, listing, bidPrice)
            latestBid = utils.getLatestBid(listing)
            latestBidPrice = latestBid.price
            

        # Add a comment
        elif 'comment' in request.POST:
            print(request.POST)
            comment = request.POST['comment-text']
            utils.addComment(listing, user, comment)
            comment = utils.getCommentList(listing)
    return render(request, f"auctions/listing.html", { 
        "listing" : listing, 
        "winner" : winner,
        "comments" : comments,
        "categoryList" : categoryList,
        "latestBidPrice" : latestBidPrice,
        "recentViewsList" : recentViewsList,
        "otherItemsList" : otherItemsBySeller,
        "otherSellersList" : otherSellersList,
        "listing_is_present" : listing_is_present
        })


def category(request):
    categoryList = Listing.choices[1:]
    categoryPoster = utils.getCategoryPosters()
    finalCategoryList = []
    for i in range(len(categoryList)):
        finalCategoryList.append((categoryList[i],categoryPoster[i]))
    return render(request, f"auctions/categoryList.html", {
         "categoryList" : categoryList,
         "finalCategoryList" : finalCategoryList
         })


def categoryFiltered(request, cat):
    categoryListForDropDown = Listing.choices[1:]
    listing = Listing.objects.filter(Q(cat1=cat) | Q(cat2=cat) | Q(cat3=cat))
    categoryList = Listing.choices
    for category in categoryList:
        if cat == category[0]:
            humanReadableValue = category[1]
            break
    print(humanReadableValue)
    return render(request, f"auctions/category.html", {
        "category" : humanReadableValue,
        "listing" : listing,
        "categoryList": categoryListForDropDown
    })


def watchlist(request):
    categoryListForDropDown = Listing.choices[1:]

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block title %}
    {{category}} Listings
{% endblock %}

{% block body %}
    {% if user.is_authenticated %}
    <div class="row mb-4 mt-4 mx-auto" style="width: 94%;">
        <div class="col d-flex">
            <h3 class="pageHeading">
                Category:&nbsp;<i>{{category}} </i>
            </h3>
        </div>
    </div>
    <div class="row mx-auto" style="width: 90%;">
        {% for item in listing %}
        <div class="col-lg-3 col-6 p-0">
            <div class="card2 h-100">
                <a href="{% url 'auction:listing' item.id %}">
                    <img src="{{item.url}}" class="card-img-top" alt="{{item.title}}-image"
                        style="height: 180px; width:90%; object-fit: contain;">
                    <span class="card-title" style="padding: 30px 25px 0">{{item.title|capfirst}}</span>
                    <h5 class="card-text text-right tilePrice2">${{item.start_price}}</h5>
                </a>
            </div>
        </div>
    {% endfor %}
    </div>
    {% else %}
    <div class="jumbotron jumbotron-fluid mx-n3 mx-lg-n5 text-center" id="helloJumbotron" style="margin-top: 100px">
        <h1 class="display-2" id="jumbotron-header">Hi there!</h1>
        <p class="lead ">You need to be logged in to view this site's contents. Please <a href="{% url 'auction:login' %}">sign in</a> or <a href="{% url 'auction:register' %}">register</a> for an account if you do not have one.</p>
    </div>
    {% endif %}
{% endblock %}

auctions/templates/auctions/categoryList.html
{% extends "auctions/layout.html" %}

{% block title %}
    Category List
{% endblock %}

{% block body %}
{% if user.is_authenticated %}
<div class="row mb-4 mt-4 mx-auto" style="width: 94%;">
    <div class="col d-flex">
        <h3 class="pageHeading"> Categories </h3>
    </div>
</div>
    <div class="row mx-auto" style="width: 90%;">
        {% for categoryItem, poster in finalCategoryList %}
        <div class="col-lg-3 col-md-4" style="margin: 15px 0">
            <div class="card3 h-100">
                <a href="{% url 'auction:filteredByCat' categoryItem.0 %}">
                    <img src="{{poster.1}}" class="card-img-top" alt="{{item.title}}-image"
                    style="height: 170px; width:100%; object-fit: cover;">
                <span class="card-title" style="padding: 12px 25px 0">{{categoryItem.1}}</span>
            
                </a>
            </div>
        </div>
    {% endfor %}
    </div>
{% else %}
<div class="jumbotron jumbotron-fluid mx-n3 mx-lg-n5 text-center" id="helloJumbotron" style="margin-top: 100px">
    <h1 class="display-2" id="jumbotron-header">Hi there!</h1>
    <p class="lead ">You need to be logged in to view this site's contents. Please <a href="{% url 'auction:login' %}">sign in</a> or <a href="{% url 'auction:register' %}">register</a> for an account if you do not have one.</p>
</div>
{% endif %}
{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block title %}
Create Listing
{% endblock %}

{% block body %}
<div class="row justify-content-center">
    <div class="col-11 ">
        <h3 style="font-weight: 400;">Create Listing</h3>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-11">
        <div class="form-container" id="createFormContainer">
            <form action="{% url 'auction:create' %}" method="POST" id="createForm">
                {% csrf_token %}
                <div class="create-list-field row">
                    <div class="col-3">
                        <label for="title">Title<span style="color:red;">*</span></label>
                    </div>
                    <div class="col-9">
                        <input type="text" name="title" class="createFormTextInput">
                    </div>
                </div>
                <hr>
                <div class="create-list-field row">
                    <div class="col-3">
                        <label for="image-url">Image URL</label>
                    </div>
                    <div class="col-9">
                        <input type="url" name="image-url" class="createFormTextInput">
                    </div>
                </div>
                <hr>
                <div class="create-list-field row">
                    <div class="col-3">
                        <label for="description">Description<span style="color:red;">*</span></label>
                    </div>
                    <div class="col-9">
                        <textarea type="text" name="description" rows="4"> </textarea>
                    </div>
                    <hr>
                </div>
                <hr>
                <div class="create-list-field row create-group">
                    <div class="col-3">
                        <label>First Category (Recommended)</label>
                    </div>
                    <div class="col-9">
                        <select name="cat1">
                            {% for option in choices %}
                            <option value="{{option.0}}">{{option.1}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="create-list-field row create-group">
                    <div class="col-3">
                        <label>Second Category (Optional)</label>
                    </div>
                    <div class="col-9">
                        <select name="cat2">
                            {% for option in choices %}
                            <option value="{{option.0}}">{{option.1}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="create-list-field row create-group">
                    <div class="col-3">
                        <label>Third Category (Optional)</label>
                    </div>
                    <div class="col-9">
                        <select name="cat3">
                            {% for option in choices %}
                            <option value="{{option.0}}">{{option.1}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <hr>
                <div class="create-list-field row create-group">
                    <div class="col-3">
                        <label>Condition:</label>
                    </div>
                    <div class="col-9">
                        <select name="condition">
                            {% for condition in conditionList %}
                            <option value="{{condition.0}}">{{condition.1}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <hr>
                <div class="create-list-field row">
                    <div class="col-3">
                        <label for="price">Starting Price:</label>
                    </div>
                    <div class="col-9">
                        <input type="number" name="price">
                    </div>
                </div>
                <button class="btn btn-primary" id="createButton">Create Listing</button>
            </form>
        </div>
    </div>

</div>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
{% if user.is_authenticated %}
<div class="row mb-4 mx-auto mt-4" style="width: 94%;">
    <div class="col d-flex">
        <h3 class="pageHeading">
            {% if displayAll %}
            All Listings
            {% else %}
            Active Listings
            {% endif %}
        </h3>
        <form name="viewOption" id="viewOption" method="POST" style="display: inline-flex; margin-left: auto; margin-right: 10px">
            {% csrf_token %}
            <button class="btn btn-light"><i class="fas fa-th-large"></i></button>
            <button class="btn btn-light" name="listView"><i class="fas fa-th-list"></i></button>
        </form>
    </div>
</div>

    {% if listView %}
    {% for item in listing %}
    <a href="{% url 'auction:listing' item.id %}" id="watchlist-link">
        <div class="row watchlistItem">
            <div class="col-md-4 wlItemImg">
                <img src="{{item.url}}" alt="" id="wlItemImg-image">
            </div>
            <div class="col-md-8 wlItemInfo">
                <div class="row">
                    <div class="col wlItemTitle">
                        <h6> {{item.title|capfirst}} </h6>
                    </div>
                </div>
                <div class="row">
                    <div class="col wlItemBody">
                        <div class="info description">Description: {{item.description}}</div>
                        <div class="info">Bid starts from : ${{item.start_price}}</div>
                        {% if item.active %}
                        <div class="info">Status: Active</div>
                        {% else %}
                        <div class="info">Status: Closed</div>
                        {% endif %}
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col d-inline-flex align-self-end card-footer">
                        <small class="text-muted">Posted by : {{item.user.username|capfirst}}</small>
                    </div>
                </div>
            </div>
        </div>
    </a>
    <hr style="width: 80%">
    {% endfor %} 
    {% else %}

        <div class="row mx-auto" style="width: 90%;">
            {% for item in listing %}
            <div class="col-lg-3 col-6 p-0">
                <div class="card2 h-100">
                    <a href="{% url 'auction:listing' item.id %}">
                        <img src="{{item.url}}" class="card-img-top" alt="{{item.title}}-image">
                        <span class="card-title" >{{item.title|capfirst}}</span>
                        <h5 class="card-text text-right tilePrice2">${{item.start_price}}</h5>
                    </a>
                </div>
            </div>
        {% endfor %}
        </div>
    {% endif %} 
{% else %}
<div class="col p-0">
    <div class="jumbotron jumbotron-fluid mx-n3 mx-lg-n5 text-center" id="helloJumbotron" style="margin-top: 100px">
        <h1 class="display-2" id="jumbotron-header">Hi there!</h1>
        <p class="lead ">You need to be logged in to view this site's contents. Please <a href="{% url 'auction:login' %}">sign in</a> or <a href="{% url 'auction:register' %}">register</a> for an account if you do not have one.</p>
</div>
</div>

{% endif %}
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <div class="container text-center " style="margin-top: 80px">
        <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auction:login' %}" method="POST" id="form" class="mx-auto mt-4 mb-3 text-left">
        {% csrf_token %}
        <div class="form-group floatingLabelField">
            <input class="form-control" type="text" name="username" id="username" required placeholder="Username">
            <label for="username" class="label">Username</label>
        </div>
        <div class="form-group floatingLabelField">
            <input class="form-control" type="password" name="password" id="password" required placeholder="Password">
            <label for="password" class="label">Password</label>
        </div>
        <input class="btn btn-primary" type="submit" name="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auction:register' %}">Register here.</a>
    </div>
    

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="container text-center"  style="margin-top: 80px">
    <h2>Register</h2>

    {% if message %}
    <div>{{ message }}</div>
    {% endif %}

    <div class="form-container" >
        <form action="{% url 'auction:register' %}" method="POST" id="form" class="mx-auto mt-0 mb-3 text-left">
            {% csrf_token %}
            <div class="form-group floatingLabelField">
                <input class="form-control" type="text" name="username" id="username" required placeholder="Username">
                <label for="username" class="label">Username</label>
            </div>
            <div class="form-group floatingLabelField">
                <input class="form-control" type="email" name="email" id="email" required placeholder="Email Address">
                <label for="email" class="label">Email Address</label>
            </div>
            <div class="form-group floatingLabelField">
                <input class="form-control" type="password" name="password" id="password" required placeholder="Password">
                <label for="password" class="label">Password</label>
            </div>
            <div class="form-group floatingLabelField">
                <input class="form-control" type="password" name="confirmation" id="confirmation" required placeholder="Confirm Password">
                <label for="confirmation" class="label">Confirm Password</label>
            </div>
            <input class="btn btn-primary mt-4" type="submit" name="submit" value="Register">
        </form>
    </div>

    Already have an account? <a href="{% url 'auction:login' %}">Log In here.</a>
</div>


{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block title %}
Your WatchList
{% endblock %}

{% block body %}
    {% if user.is_authenticated %}
        {% if watchListItems %}
        <div class="row justify-content-center">
            <div class="col-10 mt-2">
                <h3 class="pageHeading">Your Watchlist</h3>
            </div>
        </div>
        
        <br>
        {% for item in watchListItems %}
        <a href="{% url 'auction:listing' item.id %}" id="watchlist-link">
            <div class="row watchlistItem">
                <div class="col-md-4 wlItemImg">
                    <img src="{{item.url}}" alt="" id="wlItemImg-image">
                </div>
                <div class="col-md-8 wlItemInfo">
                    <div class="row">
                        <div class="col wlItemTitle">
                            <h6> {{item.title|capfirst}} </h6>
                        </div>
                        <form method="POST" id="watchlist">
                            {% csrf_token %}
                            <button class="btn pr-3 mt-n3" id="watchlistButton" type="submit" form="watchlist"
                                name="{{item.id}}-remove-watchlist"><i class="fas fa-times"></i></button>
                        </form>
                    </div>
                    <div class="row">
                        <div class="col wlItemBody">
                            <div class="info description">Description: {{item.description}}</div>
                            <div class="info">Bid starts from : ${{item.start_price}}</div>
                            {% if item.active %}
                            <div class="info">Status: Active</div>
                            {% else %}
                            <div class="info">Status: Closed</div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col d-inline-flex align-self-end card-footer">
                            <small class="text-muted">Posted by : {{item.user.username|capfirst}}</small>
                        </div>
                    </div>
                </div>
            </div>
        </a>
        <hr style="width: 80%">
        {% endfor %}
        {% else %}
        <div class="row justify-content-center text-center mt-5">
            <div class="col-10 mt-2">
                <h3 style="font-weight: 400;">You have no items in your watchist right now.</h3>
            </div>
        </div>
        {% endif %}

    {% else %}
    <div class="jumbotron jumbotron-fluid mx-n3 mx-lg-n5 text-center" id="helloJumbotron" style="margin-top: 100px">
        <h1 class="display-2" id="jumbotron-header">Hi there!</h1>
        <p class="lead ">You need to be logged in to view this site's contents. Please <a href="{% url 'auction:login' %}">sign in</a> or <a href="{% url 'auction:register' %}">register</a> for an account if you do not have one.</p>
    </div>
    {% endif %}
{% endblock %}